copilot:
  # The version of the toolkit to use (matches a Release Tag in this repo)
  version: v0.6.0

  # The collections you want to install
  collections:
    - pfe-core
    - pfe-charms
    - charm-tech-core